fix(cli): properly handle errors during type mapping
commercetools/csv-parser-price pull request #17
Opened 2016-12-12 16:01 UTC by Siilwyn

Put errors in error object and loop over errors in the error handler if
possible.

2016-12-12 17:14 UTC, hisabimbola approved these changes

2016-12-12 17:14 UTC, hisabimbola commented
Tests are failing on travis, please fix before merging

2016-12-13 06:22 UTC, hisabimbola requested changes
Can we get the coverage back to 100% 😉 😜

2016-12-13 09:12 UTC, Siilwyn commented
... This is exactly what you mentioned, going for the 100% as a goal. :P
Just commented that line out for now, don't want to waste time on it.

2016-12-13 09:12 UTC, merged